# Ordliste

```{r, echo=FALSE, results='asis'}
# cat(readLines('np.html'))
source("indeks.R")
```



```{r start,echo=FALSE,warning=FALSE,include=FALSE}
#pacman autoload evt. manglende pakker
if (!require("pacman")) install.packages("pacman")
pacman::p_load(Cairo,timeDate, DT,plotly,rio,exams,e1071,WriteXLS,readxl,maps,knitr,kableExtra,ggplot2,openxlsx,quantmod,highcharter,forecast,tippy,dplyr) #load various packages
```









```{r test2, echo=FALSE, message=FALSE}
library(DT)
# library(lubridate)
# library(MMWRweek)
library(dplyr)



skema <- tibble(indeks[,1],indeks[,2])


colnames(skema) = c('Begreb', "Forklaring")


datatable(skema, rownames = FALSE, extensions = 'Buttons',class = 'cell-border hover compact', escape = FALSE,  options = list(searchHighlight = TRUE,pageLength = 50,dom = 'Bfrt',language = list(url = '////cdn.datatables.net/plug-ins/1.10.20/i18n/Danish.json'),
    buttons = c('pdf', 'excel'),autoWidth = TRUE, columnDefs = list(list(className = 'dt-left', targets = 0:0))))%>%
  formatStyle('Begreb',  fontWeight = 'bold')%>%
  formatStyle(
  'Forklaring',
  target = 'row',
  color = styleEqual(0, 'white'),
  backgroundColor = styleEqual(c(0,8), c('lightgray',"red"))
)




```
